### ISSUE TITLE
Question: About md_index generation

### ISSUE THREAD

**Issue by x1a0k3** [joxeankoret/diaphora#130]
I'm just confused about the method or algorithm used in the generation of md_index, hope you can answer this, thank you

**Comment by joxeankoret** [comment]
The MD-Index algorithm was invented by Thomas Dullien (@thomasdullien), Ero Carrera (@erocarrera), Soeren-Meyer Eppler (@BuschnicK) & Sebastian Porst (@sporst) and explained in this paper [Automated Attacker Correlation for Malicious Code](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.661.9484&rep=rep1&type=pdf). Diaphora's implementation was added by @joeleong. 

I think it would be better if any of the aforementioned guys explain it instead of me.

**Comment by x1a0k3** [comment]
thank you very much, I'll read that paper!

**Comment by thomasdullien** [comment]
Hey there,

quick summary:

The basic idea is to take a graph, transform it into a set of
tuples/vectors (indegree/outdegree of source/dest, topological order for
every edge in the graph),
and to then hash this set of tuples/vectors in a way that is commutative.

Cheers,
Thomas

Am Mo., 12. Nov. 2018 um 03:20 Uhr schrieb Xiaoke <notifications@github.com

**Comment by x1a0k3** [comment]
Thank you Thomas, I've known that by analyzing the source code.It's a good way to use md_index represent a callgraph
