### ISSUE TITLE
Results never showing

### ISSUE THREAD

**Issue by kiwidoggie** [joxeankoret/diaphora#149]
For some reason, when I run the main script diaphora.py, it will do the diffing, but the results window never shows. If I open it from Plugins->Show Results, or press F3 neither open any windows. I don't know if my IDA config is boned, or if this was a bug introduced recently. (could be either or)

**Comment by joxeankoret** [comment]
Doesn't make any sense to me. Is some error shown somewhere? Also, can you tell me IDA version + Operating System? Does it happen diffing any and all databases or only with some specific one?

**Comment by kiwidoggie** [comment]
I am using Linux version of IDA 7.2. It seems to happen no matter which db, the diffing happens but the results windows never show. There is no error in the logs, messagebox or anything. I'll close this and re-install IDA.

**Comment by joxeankoret** [comment]
There is only one reason why there would be no window shown at all: there is no match. However, the "Unmatched" tabs should appear.

Can you give me some instructions about how to reproduce? Because, I mostly only use the Linux version of IDA and I'm using 7.2 too. I don't think reinstalling IDA will help, by the way. It looks something from your environment, not from IDA itself.
