### ISSUE TITLE
Adjust the width of left and/or right panel in the 2 sides text diff window

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#15]
Sometimes, it doesn't look ok and either the left or right panel has a very different size, that looks odd.

**Comment by joxeankoret** [comment]
My guess is that it can be "fixed" with CSS. Any idea?

**Comment by moebiuz** [comment]
It can't be fixed with CSS because each complete line (both columns; 6 columns in fact) is constructed with an unique <tr>.

I think it can be fixed if you are willing to include a patched difflib.py with Diaphora. I can look into it if you are ok with that.

Anyways, half of the problem can be fixed with 

self.browser.setLineWrapMode(QtGui.QTextEdit.NoWrap)

as it disallows to resize the first column if the window is not big enough, although I wasn't able to show an horizontal scrollbar.

**Comment by joxeankoret** [comment]
You're right! Patch applied in my local version, I will upload it among with other changes "soon".
Thanks @moebiuz!

**Comment by TheRealTroff** [comment]
Still struggling with this. Is there some way to determine the relative widths? I'd imagine there is some kind of sliderish component one could use? Failing that, would it at least be possible to set them to be of equal widths?

**Comment by joxeankoret** [comment]
@TheRealTroff, have you tried the patch offered by @moebiuz ? I haven't applied it because sometimes I don't like how the source is shown. But this is a personal opinion.

Please if you haven't checked it yet, take a look and let me know what do you think!

**Comment by TheRealTroff** [comment]
If by patch you mean uncomment the setLineWrap line, then it helps, but now the problem is that I only see one at a time because there are some long C++-type names making each side a few 1000 chars wide. I do get a horizontal scrollbar though. 

Now that I know where to look I might be able to find something that works better.

**Comment by joxeankoret** [comment]
I don't really know how to properly fix this. Perhaps creating a dialog with 2 multi-line text boxes and do the scrolling synchronization myself? Seems like the only option. But likely problematic knowing how IDAPython works.

**Comment by joxeankoret** [comment]
BTW, can an external diffing tool be a possible partial solution for that? One could use the common differ or run an external tool (kompare, bcompare, windiff or whatever) for specific cases.

**Comment by TheRealTroff** [comment]
Sure, but then you lose all hope of making the diff "live" in Ida.

I made a solution that worked for me based on style sheets/light post
processing of the html when viewed in a browser. Unfortunately QTextBrowser
couldn't care less about the width property and Ida doesn't come with
QWebEngineView.

So I'm generating my own html now based on the output of _mdiff and then
clipping to some hardcoded/configurable length.

**Comment by TheRealTroff** [comment]
If I get github correctly, please see PR #63. Caveats:
* I didn't bother to recreate the "jump to next change" column. This is not just laziness, but since it's a plain textual diff any change in location or register allocation will generate a change, which means you'll get spammed with differences anyway. 
* There's currently no way to configure the truncation column, although it is an argument with a reasonable default.
* I will almost certainly try to evolve the style used to use the colo(u)rs from the color scheme (Yes, I'm one of those l33t h4x0r Consonance users...), although for now I've kept the drab `difflib` view of the world.

**Comment by joxeankoret** [comment]
I will take a look to try to properly fix the possible problems soon. I will be on holidays until next week. I will do it as soon as I return back.

**Comment by joxeankoret** [comment]
More than one year later... the only proper fix I can see is creating an independent GUI tool, which is outside of the current scope. Closing "for now".
