### ISSUE TITLE
Same name heuristic missing many functions

### ISSUE THREAD

**Issue by mspublic** [joxeankoret/diaphora#16]
I have noticed a couple issues (potentially related) in the same name heuristics.
1. The default weight of the heuristic seems rather low especially when comparing DBs with major changes. For example comparing a very old version of an file to a new one. The matching names exist (either by manual editing or by symbols) but do not appear to be weighted well. They only seem to show up when a perfect match. It would be great to have the ability to either have the ability to only compare names or to increase the score.
2. If names are slightly off the heuristic does not pick them up. For example "namedfunction" vs "_namedfunction". The addition of the "_" seems to bypass the heuristic.

**Comment by joxeankoret** [comment]
Hi,

The 1st is expected behaviour. A match for a function with the same name but heavily modified should give a low ratio. In any case, I will take a look to the ratios, to determine if it's doing it bad.

As for the 2nd point, I will take a look but I thought I had "cleaned" correctly the names (I compare both the mangled and demangled version of the names). Could you provide 2 IDBs/binaries so I can reproduce this?

**Comment by mspublic** [comment]
Seems to have been fixed in 1.0.2/3. Much better in both areas! If i see it pop back up I will re-open. Thanks Joxean!
