### ISSUE TITLE
Ida Error "max non-trivial tinfo_t count has been reached"

### ISSUE THREAD

**Issue by leepupu** [joxeankoret/diaphora#238]
When I try to process large i64 idb (near 5G) ida pro failed to process decompiling function and pop up error meesage:
"max non-trivial tinfo_t count has been reached" and crash whole ida process

![image](https://user-images.githubusercontent.com/2727579/196112208-aa6417ff-9e5c-439a-b271-fa375c34c949.png)

Is there any chance to catch these type of exception and just simply ignore the function so that diaphora can keep process?

I can't find any decompiler config abount the limit.

Thanks

**Comment by joxeankoret** [comment]
It's the first time I actually see this message. Diaphora does nothing especial when a decompiler error happens other than printing to the output window and continuing. I believe the problem is that this message is modal and you're in an interactive session. Can you try exporting with IDA in batch mode? You have notes about batch mode exporting here:

https://github.com/joxeankoret/diaphora/wiki/How-can-I-automate-the-diffing-process%3F

**Comment by leepupu** [comment]
I tried run with batch mode and it work perfectly.
Thanks a lot.

**Comment by joxeankoret** [comment]
You are welcome :)
