### ISSUE TITLE
Suggestion Regarding Slow Parsing Speed in IDA

### ISSUE THREAD

**Issue by gameworld2007** [joxeankoret/diaphora#298]
Could we possibly copy multiple .i64 and .bin files, open multiple instances of IDA, and then perform cluster analysis? Would this potentially increase the processing speed?

**Comment by joxeankoret** [comment]
If you are referring to exporting multiple databases, yes, it's possible and it's what I do, for example, with the testing suite. 
If you are referring to parallelize the export process, I'm afraid that won't work.

**Comment by gameworld2007** [comment]
I mean, duplicating multiple instances of IDA to let Diaphora work with multiple processes, speeding up the analysis results.

**Comment by joxeankoret** [comment]
Do you refer to the exporting or the diffing process? Because the diffing process is already parallelized (using threads), and the exporting process, considering that IDA can only open one single instance of a database and IDA APIs aren't multithreading, cannot be parallelized except by doing ugly workarounds like duplicating the same database a number of times, exporting ranges of functions, and then integrating results from each analysis into a single final SQL database. If what you are referring to is this last scenario, sorry, I won't implement it. If it's not, please tell me and I will explore it.

**Comment by gameworld2007** [comment]
thanks
