### ISSUE TITLE
Diaphora handing on 'Related compilation unit'

### ISSUE THREAD

**Issue by krystalgamer** [joxeankoret/diaphora#299]
I have two 5Mb EXEs that each generate a 400Mb~ db. (30k functions)

The diffing gets stuck on `Finding with heuristic 'Related compilation unit'

![image](https://github.com/joxeankoret/diaphora/assets/4885534/4f835713-6c8f-4d70-b304-aeb3e4c115bb)

Is there a way to get more insights on what's going on?

**Comment by joxeankoret** [comment]
Uhm... I'm afraid there is little to do here. Take a look to this:

https://github.com/joxeankoret/diaphora/blob/a3f9be07978b5261b838934775162ce3e35874db/diaphora.py#L3518

It looks to me that the SQL queries are running for very-very long. So, your options are:

1. Run the SQL queries outside of Diaphora with a tool like SQLitebrowser or something like this and see how long they take. I can help you with this if you need help.
2. Disable it by writing a Diaphora script and just returning `False` when `on_special_heuristic` event happens when `heur == "Related compilation unit"`. 
3. Let it run for whatever time it requires.

For option #2, you have an example skeleton script here: https://github.com/joxeankoret/diaphora/blob/master/hooks/hooks_example2.py#L101. Again, if you need help, tell me.

**Comment by krystalgamer** [comment]
Hey sorry late response. Didn't catch the notification. Will try to update this as soon as I can access my setup!

**Comment by joxeankoret** [comment]
I have marked this heuristic as slow, as it was causing problems to some reversers. As so, I'm closing this issues, but please reopen it if you think it's required.
