### ISSUE TITLE
sqlite export crashes, and missing diff results

### ISSUE THREAD

**Issue by spokeex** [joxeankoret/diaphora#302]
Used current diaphora version in combination with current IDA 8.4 home version.

When performing the sqlite export on Windows 10 dwmcore.dll, IDA crashes. An empty sqlite crash file is created.
When restarting IDA and running the sqlite export again, I am asked if I want to continue. It then finishes without crashing.
Same behavior for the second file.

When performing the diff, I only see the 'Best Matches' and a single function in another tab (can't remember which one). The two other tabs, which I've read should be there, don't exist. All in all, I see zero functions that have changed.

There is an almost 20kb size difference between these files. The secondary contains patches for the first.

Tested the export and diff on two slightly different hello world programs. Different "Hello World" strings and different return codes from main (verified with disassembly). No sqlite export crashes, but also no differences show up in the diff.

**Comment by joxeankoret** [comment]
Hi!

I will try to reproduce the problems with dwmcore.dll on my side but if would be better if you can tell me how it crashed: did IDA crash? Diaphora crashed showing some Python stack trace? Did IDA gracefully handled whatever 'crash' happened?

By the way, regarding the differences you see (or you don't see): when a Windows DLL is updated, sometimes, there is no real code change on it, so diffing against the previous version and seeing no code change can be normal.

>Different "Hello World" (...) No sqlite export crashes, but also no differences show up in the diff.

Too small programs aren't really supported because too small functions tend to generate false positives and Diaphora ignores so many of them in order to prevent causing false positives. Please enable "Use probably unreliable methods" and try again. If it doesn't work for these trivial programs, you can try changing the following directives in `diaphora_config.py`:

* `DIFFING_MATCHES_MIN_BBLOCKS`. By default, in so many heuristics only functions with 3 or more basic blocks are considered.
* `SQL_DEFAULT_POSTFIX`. By default, functions with 5 or less instructions are ignored.

Please consider that by tuning these configuration directives to work with hello-world size programs is going to cause problems with real-world programs (but you can always set them to the previously set values).

**Comment by spokeex** [comment]
Hello, thanks for the reply.

IDA crashes. No stack trace or error windows. The program instantly terminates.
Using a simple script to compare the function disasm (after normalization), and then double checking a couple of functions manually, I have verified that there are code differences between the dwmcore.dll versions I have.

For the hello world binary, I used "Use probably unreliable methods" and modified the python variables (min 1 block, min 1 instruction), but it didn't make a difference.

I'm using Windows 11.

**Comment by joxeankoret** [comment]
Please share the dwmcore.dll libraries that are causing IDA to crash so I can try to repro.

**Comment by tankbusta** [comment]
I'm also able to reproduce a hard IDA crash on my Windows 11 install with `dwmcore.dll` on 8.4 Home & Pro versions. It also happens on pretty much everything I throw into Diaphora as it crashes with `KernelBase.dll`, `kernel32.dll`, and others. In some instances like @spokeex, I'm able to restore from the crash and it'll complete but more often than not, I can't get a generated sqlite database. I've left the default options as well as trying "Use probably unreliable methods" with no luck. 

Python 3.10.5

IDA Pro - Version 8.4.240320
IDA Home - Version 8.4.240527

The only log I can find is this crash in the Windows Application logs:
```
Faulting application name: ida64.exe, version: 8.4.24.320, time stamp: 0x8430fe9c
Faulting module name: ucrtbase.dll, version: 10.0.19041.789, time stamp: 0x2bd748bf
Exception code: 0xc0000409
Fault offset: 0x000000000007286e
Faulting process id: 0xd4c
Faulting application start time: 0x01dab21ed1113c96
Faulting application path: C:\Program Files\IDA Pro 8.4\ida64.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
```

[dwmcore.zip](https://github.com/joxeankoret/diaphora/files/15491728/dwmcore.zip)

**Comment by joxeankoret** [comment]
This looks to me like a Windows only IDA bug. I cannot reproduce in Linux, I will try to repro in various Windows installs...

**Comment by joxeankoret** [comment]
I cannot reproduce the crash exporting `dwmcore.dll` in Windows with neither IDA version 8.4.240215 nor with version 8.4.240527.

Do you have some native plugin, perhaps, that might be causing some conflict?

**Comment by tankbusta** [comment]
The only native plugin I had installed was BinDiff 8 but I uninstalled it (and deleted the DLLs because the installer doesn't remove them) but I'm still getting crashes. I installed v8.4.240320 in a clean Windows 10 VM and get the same crash. This does seem like an IDA bug but it's weird you're not able to reproduce.. I'm not sure where to go next.

**Comment by spokeex** [comment]
I only had default plugins at the time of running into the bug. The only noteworthy thing about my setup is that I uninstalled IDA free after installing IDA home.

Later, I tried bindiff and it seems to hang on exporting as well (for both dwmcore.dll and the helloworld.exe). Maybe these bugs have the same IDA bug root cause.

**Comment by joxeankoret** [comment]
@tankbusta @spokeex I'm going to setup some VMs with Windows 10 and Windows 11, but it would be cool if you could contact the Hex-Rays people because it looks like a Windows only IDA bug that, so far, I cannot reproduce on my end, but they probably can (they do have more resources than I).

**Comment by tankbusta** [comment]
After some additional testing with more binaries, I can't replicate the bug anymore so I do believe SP2 fixes this. Can you confirm @spokeex this update fixes your issues too?

**Comment by joxeankoret** [comment]
Thank you very much for the testing & reporting @tankbusta!

**Comment by spokeex** [comment]
With the new IDA home version (8.4.240527), diaphora works great

**Comment by joxeankoret** [comment]
Thanks for the verification @spokeex!
