### ISSUE TITLE
Feature Request: Additional heuristic for comparing basic blocks #2

### ISSUE THREAD

**Issue by moshekaplan** [joxeankoret/diaphora#43]
If the only difference between two blocks is terminating with a conditional jump, but the condition is reversed (for example: jz instead of a jnz), and the blocks it jumps to are the same (aside from being reversed), they should be considered equivalent.

**Comment by joxeankoret** [comment]
Uhm... I will think about possible heuristics or modifying existing heuristics. Perhaps we could simply consider what kind of instruction it's (i.e., instead of JNZ/JZ, it's "an unconditional jump").

**Comment by joxeankoret** [comment]
There is one little problem with this kind of heuristic: what if the developers fixed an existing error instead of it being a compiler chosen optimization/modification? For example: http://xenbits.xen.org/xsa/xsa136.patch

Such heuristics are a bit dangerous as Diaphora can be used for various different purposes like finding vulnerabilities (where small changes matter) or importing symbols (where small changes doesn't really matter).

**Comment by joxeankoret** [comment]
With call-graph based matching, I believe this can be improved. Closing for now, unless we really need to open it.
