### ISSUE TITLE
Support status for IDA 6.7

### ISSUE THREAD

**Issue by v-p-b** [joxeankoret/diaphora#71]
The Diaphora website states:

> As of today, however, both 6.7, 6.8 and 6.9 are supported. Version 6.6 "should work" (with all the last patches that were supplied to customers), but no support is offered for neither 6.6 nor 6.7. 

Based on this, the status of support for 6.7 is not crystal clear for me, but it seems that API changes broke Diaphora on IDA 6.7.

In particular, the IDAPython version available for 6.7 in binary (1.7.1) doesn't contain support for the ctree_* IDA structures required by Diaphora. I'm not sure if this is the result of the IDAPython releases being outdated (this could be resolved by compiling it from source I guess) or new API introduced in IDA 6.8 that is only covered by IDAPython 1.7.2.

Could you please clarify the situation?

**Comment by joxeankoret** [comment]
Hey! Diaphora used to work with IDA 6.7 but "Show diff in a graph" did not work due to lack of features and there were some bugs affecting IDA Python 6.7. After the release of 6.9 and 6.95, I decided not to maintain a partial version for IDA 6.7, as I want to maintain only the latest 2 releases (as of today, 6.8, 6.9 and 6.95).

I'm sorry, but maintaining old versions forces to write many workarounds (if at all possible) that makes the code too ugly and sometimes over complex.

**Comment by v-p-b** [comment]
Discontinuing support for old versions is fine and understood. What I'm trying to say is that 6.7 support now seems fully broken (not just some bugs). Could you update the website so people can spare themselves some trouble (and bug reports)?

**Comment by joxeankoret** [comment]
You're right. I have modified the web page to state that neither 6.6 nor 6.7 are supported any more.
Thanks for pointing it out!
