### ISSUE TITLE
OverflowError: Python int too large to convert to SQLite INTEGER

### ISSUE THREAD

**Issue by Fire30** [joxeankoret/diaphora#89]
Traceback (most recent call last):
  File "C:/Users/tj/Desktop/diaphora\diaphora_ida.py", line 1046, in import_all
    self.do_import_all(items)
  File "C:/Users/tj/Desktop/diaphora\diaphora_ida.py", line 1027, in do_import_all
    self.import_items(items)
  File "C:/Users/tj/Desktop/diaphora\diaphora_ida.py", line 1005, in import_items
    self.do_import_one(ea1, ea2)
  File "C:/Users/tj/Desktop/diaphora\diaphora_ida.py", line 984, in do_import_one
    self.import_instruction_level(ea1, ea2, cur)
  File "C:/Users/tj/Desktop/diaphora\diaphora_ida.py", line 931, in import_instruction_level
    cur.execute(sql, (ea1, ea2))
OverflowError: Python int too large to convert to SQLite INTEGER

I get the following when clicking on "import \*all\* functions". It is a FreeBSD kernel binary if that helps at all.

**Comment by xorstream** [comment]
This is caused by unsigned 64bit addresses that are outside the bounds of the signed 64bit integers used by SQL.

```BIGINT datatype in SQL Server have range of -2^63 (-9,223,372,036,854,775,808) to 2^63-1 (9,223,372,036,854,775,807).```

However an unsigned address such as 0xFFFFFFFF82541430 is equal to 18446744071601132592, which is out of these bounds.

The python variables storing ea1 and ea2 for the bug mentioned here are strings, but I guess the execute() instruction is causing some conversion to INTEGER.

**Comment by joxeankoret** [comment]
> It is a FreeBSD kernel binary if that helps at all.
Yes, it does, as this kind of bug appears with kernels usually. I thought I had removed all instances of that bug. I will fix it, hopefully, by today.

**Comment by joxeankoret** [comment]
Please take a look to this patch. It should fix any possible OverflowError bug. Hopefully (as it's a recurrent bug).
