### ISSUE TITLE
[FP] Perfect match, same name, low ratio

### ISSUE THREAD

**Issue by AVJoKe** [joxeankoret/diaphora#9]
Hi, 

after you fixed the last FP with the 0.0 ratio, I have a different FP with the same name and a low ratio. Maybe it would make sense to add some checks of the node or edge count when a perfect match based on the name is found?

![capture](https://cloud.githubusercontent.com/assets/11389175/7083844/f16851d2-df66-11e4-908d-3d8b4be8bab8.PNG)

Regards, 
Jo.

**Comment by joxeankoret** [comment]
Hi,

The problem is: what if you're looking for differences in existing functions with new binaries? For example: yesterday night I was taking a look to the new functionality added in Avast for Linux x86_64. There are many functions with the same name (taken from the symbols) but with a complete different graph, etc... The function name are the same but the functionality, naturally, can be very pretty different, thus giving these low ratios.

There is a new feature I added to ignore the matches for IDA's auto-generated function names (sub_*).  But it doesn't apply to your case (fnInternetCallback is not an IDA's automatically generated function name). I don't think there is an easy solution for this. Unless we ignore all function names. Do you think that adding such an option can be any useful?

**Comment by AVJoKe** [comment]
Oh yeah you´re right, but as an additional option this sounds useful to me.
There are definitely cases where it would help to disable the same name
matching ( including sym and sub_* ). Or maybe in general a "expert" mode
which allows the user to be more flexible and configure which of the
heuristics should be used.

Hi,
>
> The problem is: what if you're looking for differences in existing
> functions with new binaries? For example: yesterday night I was taking a
> look to the new functionality added in Avast for Linux x86_64. There are
> many functions with the same name (taken from the symbols) but with a
> complete different graph, etc... The function name are the same but the
> functionality, naturally, can be very pretty different, thus giving these
> low ratios.
>
> There is a new feature I added to ignore the matches for IDA's
> auto-generated function names (sub_*). But it doesn't apply to your case
> (fnInternetCallback is not an IDA's automatically generated function name).
> I don't think there is an easy solution for this. Unless we ignore all
> function names. Do you think that adding such an option can be any useful?
>
>
>

**Comment by joxeankoret** [comment]
Uhm... I'll add the option to ignore all the names. It will be disabled by default.

**Comment by joxeankoret** [comment]
For now, I added the option to ignore all function names (thus, disabling the 'Same name' heuristic) with commit b024b41ed4bff06fbb77173ec315d93414149f49. In the future, I will likely add a list showing all the heuristics letting the analyst select which heuristics are enabled or disabled. It requires thinking about how to do so properly.

**Comment by AVJoKe** [comment]
Perfect, thanks!
